### ISSUE TITLE
Flash of close button on page load

### ISSUE THREAD

**Issue by adamstddrd** [netlify/netlify-ui-community-nav#7]
In both Safari 14.1 and Chrome latest, a "x" button briefly flashes on page load. Here's a gif of a few page reloads in a row (it doesn't seem to be a one time deal):
<img width="803" alt="Screen Shot 2021-06-17 at 3 00 02 PM" src="https://user-images.githubusercontent.com/1004539/122479286-a7ec2780-cf7f-11eb-800a-cd91e814a1af.png">

**Comment by zachleat** [comment]
PR up for review!
